package me.silvertriclops.getcarescraper;

public class Strings {
	public static String[][] needs = {
			{"1", "Arts/Culture/Recreation", "10"},
			{"2", "Clothing/Personal/Household Needs", "7"},
			{"3", "Disaster Services", "31"},
			{"4", "Education", "22"},
			{"5", "Employment", "7"},
			{"6", "Food/Meals", "9"},
			{"7", "Government/Economic Services", "14"},
			{"8", "Healthcare", "75"},
			{"19", "Housing", "16"},
			{"12", "Income Support/Assistance", "23"},
			{"10", "Individual, Family & Community Support", "47"},
			{"11", "Information Services", "4"},
			{"13", "Legal, Consumer, and Public Safety", "40"},
			{"14", "Mental Health/Addictions", "33"},
			{"15", "Transportation", "4"},
			{"20", "Utility Assistance", "2"},
			{"16", "Volunteers/Donations", "4"}
	};
	
	public static String[][] programs = {
			{"1", "Arts/Culture/Recreation", "Arts", "Arts"},
			{"1", "Arts/Culture/Recreation", "Camps/Parks", "Camps/Parks"},
			{"1", "Arts/Culture/Recreation", "Clubs", "Clubs"},
			{"1", "Arts/Culture/Recreation", "Cultural Heritage", "Cultural Heritage"},
			{"1", "Arts/Culture/Recreation", "Historic Preservation", "Historic Preservation"},
			{"1", "Arts/Culture/Recreation", "Inauguration", "Inauguration"},
			{"1", "Arts/Culture/Recreation", "Physical Fitness", "Physical Fitness"},
			{"1", "Arts/Culture/Recreation", "Recreation", "Recreation"},
			{"1", "Arts/Culture/Recreation", "Travel Opportunities", "Travel Opportunities"},
			{"1", "Arts/Culture/Recreation", "Youth Development", "Youth Development"},
			{"2", "Clothing/Personal/Household Needs", "Automobiles", "Automobiles"},
			{"2", "Clothing/Personal/Household Needs", "Cell Phones", "Cell Phones"},
			{"2", "Clothing/Personal/Household Needs", "Clothing", "Clothing"},
			{"2", "Clothing/Personal/Household Needs", "Fans/Air Conditioners", "Fans/Air Conditioners"},
			{"2", "Clothing/Personal/Household Needs", "Household Items", "Household Items"},
			{"2", "Clothing/Personal/Household Needs", "Personal Grooming Needs", "Personal Grooming Needs"},
			{"2", "Clothing/Personal/Household Needs", "Thrift Shops", "Thrift Shops"},
			{"3", "Disaster Services", "Cold Weather/Warming Centers", "Cold Weather/Warming Centers"},
			{"3", "Disaster Services", "Disaster Closings", "Disaster Closings"},
			{"3", "Disaster Services", "Disaster Clothing/Emergency Supplies", "Disaster Clothing/Emergency Supplies"},
			{"3", "Disaster Services", "Disaster Donations Coordination", "Disaster Donations Coordination"},
			{"3", "Disaster Services", "Disaster Evacuation Centers", "Disaster Evacuation Centers"},
			{"3", "Disaster Services", "Disaster Food Stamps", "Disaster Food Stamps"},
			{"3", "Disaster Services", "Disaster Loans", "Disaster Loans"},
			{"3", "Disaster Services", "Disaster Management Organizations", "Disaster Management Organizations"},
			{"3", "Disaster Services", "Disaster Preparedness", "Disaster Preparedness"},
			{"3", "Disaster Services", "Disaster Recovery", "Disaster Recovery"},
			{"3", "Disaster Services", "Disaster Related Drinking Water", "Disaster Related Drinking Water"},
			{"3", "Disaster Services", "Disaster Related Dry Ice", "Disaster Related Dry Ice"},
			{"3", "Disaster Services", "Disaster Related Extreme Heat Cooling Centers", "Disaster Related Extreme Heat Cooling Centers"},
			{"3", "Disaster Services", "Disaster Related Ice", "Disaster Related Ice"},
			{"3", "Disaster Services", "Disaster Related Mass Feeding Sites", "Disaster Related Mass Feeding Sites"},
			{"3", "Disaster Services", "Disaster Response", "Disaster Response"},
			{"3", "Disaster Services", "Disaster Service Centers/Hotlines", "Disaster Service Centers/Hotlines"},
			{"3", "Disaster Services", "Disaster Services For Animals", "Disaster Services For Animals"},
			{"3", "Disaster Services", "Disaster Shelters", "Disaster Shelters"},
			{"3", "Disaster Services", "Disaster Transportation", "Disaster Transportation"},
			{"3", "Disaster Services", "Disaster Volunteers", "Disaster Volunteers"},
			{"3", "Disaster Services", "Disaster Warnings", "Disaster Warnings"},
			{"3", "Disaster Services", "Post Disaster Family Adoption Programs", "Post Disaster Family Adoption Programs"},
			{"3", "Disaster Services", "Post Disaster Housing Assistance", "Post Disaster Housing Assistance"},
			{"3", "Disaster Services", "Post Disaster Legal Counseling", "Post Disaster Legal Counseling"},
			{"3", "Disaster Services", "Post Disaster Mental Health Services", "Post Disaster Mental Health Services"},
			{"3", "Disaster Services", "Post Disaster Safety Inspection/Evaluation", "Post Disaster Safety Inspection/Evaluation"},
			{"3", "Disaster Services", "Post Disaster Shelter Services", "Post Disaster Shelter Services"},
			{"3", "Disaster Services", "Post Disaster Temporary Transportation", "Post Disaster Temporary Transportation"},
			{"3", "Disaster Services", "Post Disaster Utility Restoration", "Post Disaster Utility Restoration"},
			{"3", "Disaster Services", "VOAD - Voluntary Organizations Active in Disaster", "VOAD - Voluntary Organizations Active in Disaster"},
			{"4", "Education", "Adult Education", "Adult Education"},
			{"4", "Education", "Alternative Education", "Alternative Education"},
			{"4", "Education", "College/University", "College/University"},
			{"4", "Education", "Continuing Education", "Continuing Education"},
			{"4", "Education", "Counseling-Guidance", "Counseling-Guidance"},
			{"4", "Education", "Dropout Programs", "Dropout Programs"},
			{"4", "Education", "Early Head Start", "Early Head Start"},
			{"4", "Education", "ESL-English as a 2nd Language", "ESL-English as a 2nd Language"},
			{"4", "Education", "Financial Aid-Education", "Financial Aid-Education"},
			{"4", "Education", "GED Instruction", "GED Instruction"},
			{"4", "Education", "Head Start", "Head Start"},
			{"4", "Education", "Literacy Programs", "Literacy Programs"},
			{"4", "Education", "Preschools", "Preschools"},
			{"4", "Education", "School-Alternative", "School-Alternative"},
			{"4", "Education", "School Health Programs", "School Health Programs"},
			{"4", "Education", "School-Private", "School-Private"},
			{"4", "Education", "School-Public", "School-Public"},
			{"4", "Education", "School Readiness", "School Readiness"},
			{"4", "Education", "Special Education", "Special Education"},
			{"4", "Education", "Teen Parents", "Teen Parents"},
			{"4", "Education", "Tutoring", "Tutoring"},
			{"4", "Education", "Vocational Education", "Vocational Education"},
			{"5", "Employment", "Employment & Career Services", "Employment & Career Services"},
			{"5", "Employment", "Job Bank/Listing", "Job Bank/Listing"},
			{"5", "Employment", "Job Training", "Job Training"},
			{"5", "Employment", "National Service Programs", "National Service Programs"},
			{"5", "Employment", "Supported Employment", "Supported Employment"},
			{"5", "Employment", "Veteran Employment", "Veteran Employment"},
			{"5", "Employment", "Vocational Rehabilitation", "Vocational Rehabilitation"},
			{"6", "Food/Meals", "Agriculture", "Agriculture"},
			{"6", "Food/Meals", "Food", "Food"},
			{"6", "Food/Meals", "Food Pantry/Emergency", "Food Pantry/Emergency"},
			{"6", "Food/Meals", "Food Stamps/SNAP", "Food Stamps/SNAP"},
			{"6", "Food/Meals", "Home Delivered Meals", "Home Delivered Meals"},
			{"6", "Food/Meals", "Meal Sites", "Meal Sites"},
			{"6", "Food/Meals", "Soup Kitchens", "Soup Kitchens"},
			{"6", "Food/Meals", "Summer Food", "Summer Food"},
			{"6", "Food/Meals", "WIC/Women Infant & Children", "WIC/Women Infant & Children"},
			{"7", "Government/Economic Services", "Administrative Entities", "Administrative Entities"},
			{"7", "Government/Economic Services", "Building Inspection/Permits", "Building Inspection/Permits"},
			{"7", "Government/Economic Services", "Civic Groups", "Civic Groups"},
			{"7", "Government/Economic Services", "Economic Development", "Economic Development"},
			{"7", "Government/Economic Services", "Federal Official Offices", "Federal Official Offices"},
			{"7", "Government/Economic Services", "Government Services", "Government Services"},
			{"7", "Government/Economic Services", "Individual Development Accounts", "Individual Development Accounts"},
			{"7", "Government/Economic Services", "Local Official Offices", "Local Official Offices"},
			{"7", "Government/Economic Services", "Military Family Support", "Military Family Support"},
			{"7", "Government/Economic Services", "Military Recruitment", "Military Recruitment"},
			{"7", "Government/Economic Services", "Professional Associations", "Professional Associations"},
			{"7", "Government/Economic Services", "State Official Offices", "State Official Offices"},
			{"7", "Government/Economic Services", "Traffic Control", "Traffic Control"},
			{"7", "Government/Economic Services", "Voter Information", "Voter Information"},
			{"8", "Healthcare", "ADRC - Aging and Disability Resource Centers", "ADRC - Aging and Disability Resource Centers"},
			{"8", "Healthcare", "Affordable Healthcare - Counseling", "Affordable Healthcare - Counseling"},
			{"8", "Healthcare", "Affordable Healthcare - Eligibility", "Affordable Healthcare - Eligibility"},
			{"8", "Healthcare", "Affordable Healthcare - Marketplace", "Affordable Healthcare - Marketplace"},
			{"8", "Healthcare", "Affordable Healthcare - Virginia Healthplan", "Affordable Healthcare - Virginia Healthplan"},
			{"8", "Healthcare", "AIDS/HIV Services", "AIDS/HIV Services"},
			{"8", "Healthcare", "Assistive Technology Info", "Assistive Technology Info"},
			{"8", "Healthcare", "Autism", "Autism"},
			{"8", "Healthcare", "Blindness/Visual Impairments", "Blindness/Visual Impairments"},
			{"8", "Healthcare", "Blood/Organ Banks", "Blood/Organ Banks"},
			{"8", "Healthcare", "Breastfeeding", "Breastfeeding"},
			{"8", "Healthcare", "Cancer Clinics", "Cancer Clinics"},
			{"8", "Healthcare", "Centers for Independent Living", "Centers for Independent Living"},
			{"8", "Healthcare", "Childbirth Education", "Childbirth Education"},
			{"8", "Healthcare", "Civic Groups", "Civic Groups"},
			{"8", "Healthcare", "Clinic Medical", "Clinic Medical"},
			{"8", "Healthcare", "Communicable Diseases", "Communicable Diseases"},
			{"8", "Healthcare", "Counseling-Genetic", "Counseling-Genetic"},
			{"8", "Healthcare", "Daily Life Assessments", "Daily Life Assessments"},
			{"8", "Healthcare", "Dental Care", "Dental Care"},
			{"8", "Healthcare", "Developmental Delays", "Developmental Delays"},
			{"8", "Healthcare", "Dialysis", "Dialysis"},
			{"8", "Healthcare", "Ebola", "Ebola"},
			{"8", "Healthcare", "Emergency Medical Care", "Emergency Medical Care"},
			{"8", "Healthcare", "Eye Care", "Eye Care"},
			{"8", "Healthcare", "Family Planning", "Family Planning"},
			{"8", "Healthcare", "Financial Aid-Medical/Dental", "Financial Aid-Medical/Dental"},
			{"8", "Healthcare", "First Aid Training", "First Aid Training"},
			{"8", "Healthcare", "Foot Care", "Foot Care"},
			{"8", "Healthcare", "Health Care", "Health Care"},
			{"8", "Healthcare", "Health Departments", "Health Departments"},
			{"8", "Healthcare", "Health Education", "Health Education"},
			{"8", "Healthcare", "Health Inspections", "Health Inspections"},
			{"8", "Healthcare", "Health Screening/Diagnosis", "Health Screening/Diagnosis"},
			{"8", "Healthcare", "Hearing Impairment", "Hearing Impairment"},
			{"8", "Healthcare", "Home Health Care", "Home Health Care"},
			{"8", "Healthcare", "Hospice Care", "Hospice Care"},
			{"8", "Healthcare", "Hospitals", "Hospitals"},
			{"8", "Healthcare", "Housing-Health Related", "Housing-Health Related"},
			{"8", "Healthcare", "Hygiene", "Hygiene"},
			{"8", "Healthcare", "Immunization", "Immunization"},
			{"8", "Healthcare", "Independent Living Skills", "Independent Living Skills"},
			{"8", "Healthcare", "Maternity Home", "Maternity Home"},
			{"8", "Healthcare", "Medical Clinic-Free Clinic", "Medical Clinic-Free Clinic"},
			{"8", "Healthcare", "Medical Clinic-Private", "Medical Clinic-Private"},
			{"8", "Healthcare", "Medical Clinic-Sliding Scale", "Medical Clinic-Sliding Scale"},
			{"8", "Healthcare", "Medical Equipment/Supplies", "Medical Equipment/Supplies"},
			{"8", "Healthcare", "Medical Laboratories", "Medical Laboratories"},
			{"8", "Healthcare", "Medication", "Medication"},
			{"8", "Healthcare", "Mercy Flights", "Mercy Flights"},
			{"8", "Healthcare", "Nursing Facilities", "Nursing Facilities"},
			{"8", "Healthcare", "Nutrition Education", "Nutrition Education"},
			{"8", "Healthcare", "Occupational Health/Safety", "Occupational Health/Safety"},
			{"8", "Healthcare", "Occupational Therapy", "Occupational Therapy"},
			{"8", "Healthcare", "Options Counseling", "Options Counseling"},
			{"8", "Healthcare", "Pediatrics", "Pediatrics"},
			{"8", "Healthcare", "Physical Therapy", "Physical Therapy"},
			{"8", "Healthcare", "Physician Referrals", "Physician Referrals"},
			{"8", "Healthcare", "Poison Control", "Poison Control"},
			{"8", "Healthcare", "Pregnancy Services", "Pregnancy Services"},
			{"8", "Healthcare", "Prenatal Care", "Prenatal Care"},
			{"8", "Healthcare", "Prescription Drug Discount Card", "Prescription Drug Discount Card"},
			{"8", "Healthcare", "Prescription Monitoring", "Prescription Monitoring"},
			{"8", "Healthcare", "Prescriptions - Financial Aid", "Prescriptions - Financial Aid"},
			{"8", "Healthcare", "Public Health Nursing", "Public Health Nursing"},
			{"8", "Healthcare", "Rehabilitation", "Rehabilitation"},
			{"8", "Healthcare", "Service Animals", "Service Animals"},
			{"8", "Healthcare", "Sex Education", "Sex Education"},
			{"8", "Healthcare", "Sleep Disorders Clinics", "Sleep Disorders Clinics"},
			{"8", "Healthcare", "Speech Therapy", "Speech Therapy"},
			{"8", "Healthcare", "STD-Sexually Transmitted Disease", "STD-Sexually Transmitted Disease"},
			{"8", "Healthcare", "Support Group-Disability/Health", "Support Group-Disability/Health"},
			{"8", "Healthcare", "Tuberculosis Information", "Tuberculosis Information"},
			{"8", "Healthcare", "Veteran Outpatient Clinics", "Veteran Outpatient Clinics"},
			{"8", "Healthcare", "Weight Management", "Weight Management"},
			{"19", "Housing", "Assisted Living", "Assisted Living"},
			{"19", "Housing", "Counseling-Housing", "Counseling-Housing"},
			{"19", "Housing", "Counseling-Mortgage", "Counseling-Mortgage"},
			{"19", "Housing", "Financial Aid-Housing", "Financial Aid-Housing"},
			{"19", "Housing", "Group Home-Other", "Group Home-Other"},
			{"19", "Housing", "Homeless - Intake Central", "Homeless - Intake Central"},
			{"19", "Housing", "Housing", "Housing"},
			{"19", "Housing", "Housing-Disability Related", "Housing-Disability Related"},
			{"19", "Housing", "Housing-Rehab/Repair", "Housing-Rehab/Repair"},
			{"19", "Housing", "Housing-Seniors", "Housing-Seniors"},
			{"19", "Housing", "Housing-Subsidized", "Housing-Subsidized"},
			{"19", "Housing", "Housing-Transitional", "Housing-Transitional"},
			{"19", "Housing", "Landlord/Tenant", "Landlord/Tenant"},
			{"19", "Housing", "Respite Facilities", "Respite Facilities"},
			{"19", "Housing", "Shelter-Emergency", "Shelter-Emergency"},
			{"19", "Housing", "Shelter-Homeless", "Shelter-Homeless"},
			{"12", "Income Support/Assistance", "Counseling-Financial", "Counseling-Financial"},
			{"12", "Income Support/Assistance", "Credit Reporting Services", "Credit Reporting Services"},
			{"12", "Income Support/Assistance", "FAMIS", "FAMIS"},
			{"12", "Income Support/Assistance", "Financial Aid-Child Care", "Financial Aid-Child Care"},
			{"12", "Income Support/Assistance", "Financial Aid-Home/Community Care", "Financial Aid-Home/Community Care"},
			{"12", "Income Support/Assistance", "Financial Aid-Other", "Financial Aid-Other"},
			{"12", "Income Support/Assistance", "Food Stamps/SNAP", "Food Stamps/SNAP"},
			{"12", "Income Support/Assistance", "Homelessness Prevention", "Homelessness Prevention"},
			{"12", "Income Support/Assistance", "Identity Theft Recovery", "Identity Theft Recovery"},
			{"12", "Income Support/Assistance", "Insurance", "Insurance"},
			{"12", "Income Support/Assistance", "Medicaid", "Medicaid"},
			{"12", "Income Support/Assistance", "Medicare", "Medicare"},
			{"12", "Income Support/Assistance", "Payee Services", "Payee Services"},
			{"12", "Income Support/Assistance", "Prescription Assistance", "Prescription Assistance"},
			{"12", "Income Support/Assistance", "Social Security", "Social Security"},
			{"12", "Income Support/Assistance", "Social Services Department/DSS", "Social Services Department/DSS"},
			{"12", "Income Support/Assistance", "SSI/Supplemental Security Income", "SSI/Supplemental Security Income"},
			{"12", "Income Support/Assistance", "TANF", "TANF"},
			{"12", "Income Support/Assistance", "Tax Assessment", "Tax Assessment"},
			{"12", "Income Support/Assistance", "Taxes/Tax Relief", "Taxes/Tax Relief"},
			{"12", "Income Support/Assistance", "Tax Prep Assistance", "Tax Prep Assistance"},
			{"12", "Income Support/Assistance", "Unemployment Insurance", "Unemployment Insurance"},
			{"12", "Income Support/Assistance", "WIC/Women Infant & Children", "WIC/Women Infant & Children"},
			{"10", "Individual, Family & Community Support", "Adoption", "Adoption"},
			{"10", "Individual, Family & Community Support", "Adult Day Care", "Adult Day Care"},
			{"10", "Individual, Family & Community Support", "Adult Protective Services", "Adult Protective Services"},
			{"10", "Individual, Family & Community Support", "Animal Services", "Animal Services"},
			{"10", "Individual, Family & Community Support", "Area Agencies on Aging/AAA", "Area Agencies on Aging/AAA"},
			{"10", "Individual, Family & Community Support", "Before/After School Programs", "Before/After School Programs"},
			{"10", "Individual, Family & Community Support", "Benefits Screening", "Benefits Screening"},
			{"10", "Individual, Family & Community Support", "Burial Assistance", "Burial Assistance"},
			{"10", "Individual, Family & Community Support", "Caregiver Training", "Caregiver Training"},
			{"10", "Individual, Family & Community Support", "Case/Care Management", "Case/Care Management"},
			{"10", "Individual, Family & Community Support", "Cemeteries", "Cemeteries"},
			{"10", "Individual, Family & Community Support", "Child Care Centers", "Child Care Centers"},
			{"10", "Individual, Family & Community Support", "Child Day Care", "Child Day Care"},
			{"10", "Individual, Family & Community Support", "Child Protective Services", "Child Protective Services"},
			{"10", "Individual, Family & Community Support", "Civic Groups", "Civic Groups"},
			{"10", "Individual, Family & Community Support", "Coroner", "Coroner"},
			{"10", "Individual, Family & Community Support", "Emergency Alerts", "Emergency Alerts"},
			{"10", "Individual, Family & Community Support", "Employee Assistance Programs", "Employee Assistance Programs"},
			{"10", "Individual, Family & Community Support", "Facilities/Community Centers", "Facilities/Community Centers"},
			{"10", "Individual, Family & Community Support", "Family Home Child Care", "Family Home Child Care"},
			{"10", "Individual, Family & Community Support", "Family Preservation Programs", "Family Preservation Programs"},
			{"10", "Individual, Family & Community Support", "Federal Official Offices", "Federal Official Offices"},
			{"10", "Individual, Family & Community Support", "Foster Care", "Foster Care"},
			{"10", "Individual, Family & Community Support", "Holiday Assistance", "Holiday Assistance"},
			{"10", "Individual, Family & Community Support", "Homeless Services", "Homeless Services"},
			{"10", "Individual, Family & Community Support", "Immigrant Resettlement", "Immigrant Resettlement"},
			{"10", "Individual, Family & Community Support", "Independent Living Skills", "Independent Living Skills"},
			{"10", "Individual, Family & Community Support", "Individual Development Accounts", "Individual Development Accounts"},
			{"10", "Individual, Family & Community Support", "In Home Assistance Programs", "In Home Assistance Programs"},
			{"10", "Individual, Family & Community Support", "Local Official Offices", "Local Official Offices"},
			{"10", "Individual, Family & Community Support", "Mentoring", "Mentoring"},
			{"10", "Individual, Family & Community Support", "Parenting", "Parenting"},
			{"10", "Individual, Family & Community Support", "Planning/Funding Organizations", "Planning/Funding Organizations"},
			{"10", "Individual, Family & Community Support", "Respite Care", "Respite Care"},
			{"10", "Individual, Family & Community Support", "Self-Sufficiency Programs", "Self-Sufficiency Programs"},
			{"10", "Individual, Family & Community Support", "State Official Offices", "State Official Offices"},
			{"10", "Individual, Family & Community Support", "Support Group-Caregivers", "Support Group-Caregivers"},
			{"10", "Individual, Family & Community Support", "Support Group-Death/Grief", "Support Group-Death/Grief"},
			{"10", "Individual, Family & Community Support", "Support Group-Disability/Health", "Support Group-Disability/Health"},
			{"10", "Individual, Family & Community Support", "Support Group-Mental Health", "Support Group-Mental Health"},
			{"10", "Individual, Family & Community Support", "Support Group-Other", "Support Group-Other"},
			{"10", "Individual, Family & Community Support", "Support Group-Parenting", "Support Group-Parenting"},
			{"10", "Individual, Family & Community Support", "Support Group-Violent Anger", "Support Group-Violent Anger"},
			{"10", "Individual, Family & Community Support", "Telephone Reassurance", "Telephone Reassurance"},
			{"10", "Individual, Family & Community Support", "Translation/Interpreters", "Translation/Interpreters"},
			{"10", "Individual, Family & Community Support", "Traveler's Assistance", "Traveler's Assistance"},
			{"10", "Individual, Family & Community Support", "Welcome Programs", "Welcome Programs"},
			{"11", "Information Services", "211 Centers", "211 Centers"},
			{"11", "Information Services", "Info Lines/Specialized I&R", "Info Lines/Specialized I&R"},
			{"11", "Information Services", "Libraries", "Libraries"},
			{"11", "Information Services", "Reading Services", "Reading Services"},
			{"13", "Legal, Consumer, and Public Safety", "Advocacy", "Advocacy"},
			{"13", "Legal, Consumer, and Public Safety", "Benefits Assistance", "Benefits Assistance"},
			{"13", "Legal, Consumer, and Public Safety", "Car Seats-Infant/Child", "Car Seats-Infant/Child"},
			{"13", "Legal, Consumer, and Public Safety", "Child Care Provider Training", "Child Care Provider Training"},
			{"13", "Legal, Consumer, and Public Safety", "Child Support", "Child Support"},
			{"13", "Legal, Consumer, and Public Safety", "Consumer Complaints", "Consumer Complaints"},
			{"13", "Legal, Consumer, and Public Safety", "Consumer Education", "Consumer Education"},
			{"13", "Legal, Consumer, and Public Safety", "Consumer Protection", "Consumer Protection"},
			{"13", "Legal, Consumer, and Public Safety", "Courts", "Courts"},
			{"13", "Legal, Consumer, and Public Safety", "Crime Prevention", "Crime Prevention"},
			{"13", "Legal, Consumer, and Public Safety", "Crime Victims", "Crime Victims"},
			{"13", "Legal, Consumer, and Public Safety", "Discrimination", "Discrimination"},
			{"13", "Legal, Consumer, and Public Safety", "Domestic Violence", "Domestic Violence"},
			{"13", "Legal, Consumer, and Public Safety", "Driver Education", "Driver Education"},
			{"13", "Legal, Consumer, and Public Safety", "Driving/Traffic", "Driving/Traffic"},
			{"13", "Legal, Consumer, and Public Safety", "Emergency Rescue", "Emergency Rescue"},
			{"13", "Legal, Consumer, and Public Safety", "Emergency Signaling Devices", "Emergency Signaling Devices"},
			{"13", "Legal, Consumer, and Public Safety", "Environment", "Environment"},
			{"13", "Legal, Consumer, and Public Safety", "Ex-Offender Reentry Programs", "Ex-Offender Reentry Programs"},
			{"13", "Legal, Consumer, and Public Safety", "Fire Safety/Protection", "Fire Safety/Protection"},
			{"13", "Legal, Consumer, and Public Safety", "Gang Intervention Programs", "Gang Intervention Programs"},
			{"13", "Legal, Consumer, and Public Safety", "Immigration", "Immigration"},
			{"13", "Legal, Consumer, and Public Safety", "Jails/Prisons", "Jails/Prisons"},
			{"13", "Legal, Consumer, and Public Safety", "Landlord/Tenant", "Landlord/Tenant"},
			{"13", "Legal, Consumer, and Public Safety", "Law Enforcement", "Law Enforcement"},
			{"13", "Legal, Consumer, and Public Safety", "Lawyer Referral", "Lawyer Referral"},
			{"13", "Legal, Consumer, and Public Safety", "Legal Advice/Representation", "Legal Advice/Representation"},
			{"13", "Legal, Consumer, and Public Safety", "Licenses/Permits", "Licenses/Permits"},
			{"13", "Legal, Consumer, and Public Safety", "Licensing/Regulation", "Licensing/Regulation"},
			{"13", "Legal, Consumer, and Public Safety", "Mediation", "Mediation"},
			{"13", "Legal, Consumer, and Public Safety", "Missing Persons", "Missing Persons"},
			{"13", "Legal, Consumer, and Public Safety", "Passports", "Passports"},
			{"13", "Legal, Consumer, and Public Safety", "Pretrial Services", "Pretrial Services"},
			{"13", "Legal, Consumer, and Public Safety", "Probation Programs", "Probation Programs"},
			{"13", "Legal, Consumer, and Public Safety", "Registration/Titles/Deeds", "Registration/Titles/Deeds"},
			{"13", "Legal, Consumer, and Public Safety", "Safety Advisories", "Safety Advisories"},
			{"13", "Legal, Consumer, and Public Safety", "Safety Education", "Safety Education"},
			{"13", "Legal, Consumer, and Public Safety", "Smoke Alarms", "Smoke Alarms"},
			{"13", "Legal, Consumer, and Public Safety", "Support Group-Crime", "Support Group-Crime"},
			{"13", "Legal, Consumer, and Public Safety", "Vital Records", "Vital Records"},
			{"14", "Mental Health/Addictions", "Art Therapy", "Art Therapy"},
			{"14", "Mental Health/Addictions", "Case Management-Mental Health", "Case Management-Mental Health"},
			{"14", "Mental Health/Addictions", "Counseling", "Counseling"},
			{"14", "Mental Health/Addictions", "Counseling-Death/Grief", "Counseling-Death/Grief"},
			{"14", "Mental Health/Addictions", "Counseling-Employment Transition", "Counseling-Employment Transition"},
			{"14", "Mental Health/Addictions", "Counseling-Family", "Counseling-Family"},
			{"14", "Mental Health/Addictions", "Counseling-Gambling", "Counseling-Gambling"},
			{"14", "Mental Health/Addictions", "Counseling-Marriage", "Counseling-Marriage"},
			{"14", "Mental Health/Addictions", "Counseling-Pastoral", "Counseling-Pastoral"},
			{"14", "Mental Health/Addictions", "Counseling-Sexual", "Counseling-Sexual"},
			{"14", "Mental Health/Addictions", "Counseling-Sexual Assault", "Counseling-Sexual Assault"},
			{"14", "Mental Health/Addictions", "Counseling-Substance Abuse", "Counseling-Substance Abuse"},
			{"14", "Mental Health/Addictions", "Crisis Intervention/Prevention", "Crisis Intervention/Prevention"},
			{"14", "Mental Health/Addictions", "CSB - Community Services Boards", "CSB - Community Services Boards"},
			{"14", "Mental Health/Addictions", "Detoxification", "Detoxification"},
			{"14", "Mental Health/Addictions", "Group Home-Mental Health", "Group Home-Mental Health"},
			{"14", "Mental Health/Addictions", "Hotlines", "Hotlines"},
			{"14", "Mental Health/Addictions", "Mental Health-Inpatient", "Mental Health-Inpatient"},
			{"14", "Mental Health/Addictions", "Mental Health-Outpatient", "Mental Health-Outpatient"},
			{"14", "Mental Health/Addictions", "Mental Illness Ed/Prevention", "Mental Illness Ed/Prevention"},
			{"14", "Mental Health/Addictions", "Methadone Clinic", "Methadone Clinic"},
			{"14", "Mental Health/Addictions", "Runaway", "Runaway"},
			{"14", "Mental Health/Addictions", "Smoking Cessation", "Smoking Cessation"},
			{"14", "Mental Health/Addictions", "Substance Abuse-Day Treatment", "Substance Abuse-Day Treatment"},
			{"14", "Mental Health/Addictions", "Substance Abuse Ed/Prevention", "Substance Abuse Ed/Prevention"},
			{"14", "Mental Health/Addictions", "Substance Abuse-Halfway House", "Substance Abuse-Halfway House"},
			{"14", "Mental Health/Addictions", "Substance Abuse-Inpatient Treatment", "Substance Abuse-Inpatient Treatment"},
			{"14", "Mental Health/Addictions", "Substance Abuse-Outpatient Treatment", "Substance Abuse-Outpatient Treatment"},
			{"14", "Mental Health/Addictions", "Substance Abuse-Perinatal Treatment", "Substance Abuse-Perinatal Treatment"},
			{"14", "Mental Health/Addictions", "Substance Abuse Treatment", "Substance Abuse Treatment"},
			{"14", "Mental Health/Addictions", "Suicide Intervention", "Suicide Intervention"},
			{"14", "Mental Health/Addictions", "Support Group-Mental Health", "Support Group-Mental Health"},
			{"14", "Mental Health/Addictions", "Support Group-Substance Abuse", "Support Group-Substance Abuse"},
			{"15", "Transportation", "Financial Aid-Transportation", "Financial Aid-Transportation"},
			{"15", "Transportation", "Transportation", "Transportation"},
			{"15", "Transportation", "Transportation-Special", "Transportation-Special"},
			{"15", "Transportation", "Traveler's Assistance", "Traveler's Assistance"},
			{"20", "Utility Assistance", "Financial Aid-Utility/Fuel", "Financial Aid-Utility/Fuel"},
			{"20", "Utility Assistance", "Utility Services", "Utility Services"},
			{"16", "Volunteers/Donations", "Car Donations", "Car Donations"},
			{"16", "Volunteers/Donations", "Disaster/Emergency Services Volunteer Opportunities", "Disaster/Emergency Services Volunteer Opportunities"},
			{"16", "Volunteers/Donations", "Donations", "Donations"},
			{"16", "Volunteers/Donations", "Volunteer Programs", "Volunteer Programs"}
	};
	
}
